package schema

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/nmarsollier/cataloggo/internal/graph/model"
	"github.com/nmarsollier/cataloggo/internal/graph/resolvers"
)

// FindArticleByID is the resolver for the findArticleByID field.
func (r *entityResolver) FindArticleByID(ctx context.Context, id string) (*model.Article, error) {
	return resolvers.FindArticleByID(ctx, id)
}

// Entity returns model.EntityResolver implementation.
func (r *Resolver) Entity() model.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
